### ISSUE TITLE
ga4gh.AffiliationAndRole

### ISSUE THREAD

**Issue by MKonopko** [ga4gh-duri/ga4gh-duri.github.io#2]
https://github.com/ga4gh-duri/ga4gh-duri.github.io/blob/master/researcher_ids/RI_Claims_RFC.md#ga4ghaffiliationandrole
 From @cdvoisin

Attempted to address one of Laura's suggestions. It also suggests a means to encode a citizen scientist on a custom namespace, which may be a good or bad thing. Happy to switch this to a non-custom namespace example if someone has a good one. PTAL and let's fix as needed. Thanks!

**Comment by cdvoisin** [comment]
This may get updated as part of Stephanie's revisit of v1's standard roles. Closing this issue for now.
