### ISSUE TITLE
Restrictive URL field definition

### ISSUE THREAD

**Issue by mikael-linden** [ga4gh-duri/ga4gh-duri.github.io#24]
I'm slightly worried about this URL field definition: 
_Research institutions are RECOMMENDED to use a persistent URL pointing to established organizational ontology identifier -- whether managed directly or by a third-party service such as a GRID -- as their canonical "source" URL._ I take this as a quite strong push to use GRID URIs. 

On the other hand, section _source_ suggest also substructure: _The additional substructure MUST only encode the sub-organization or department..._. I believe GRID does not encode substructures which appears to be a conflict in the spec.

I believe for controlled access data it is typical that the data is collected in a common research project for multiple universities who then nominate the DAC. Therefore it is difficult to identify a single GRID ID for the collaboration and DAC. At least at EGA DACs have systematic URLs e.g. https://www.ebi.ac.uk/ega/dacs/EGAC00000000001 and these URLs can be easily injected to the Passport visas by EGA. I'd like to make sure the spec allows their use as source. I'm not sure if DACs have other URLs and EGA knows them.

**Comment by mikael-linden** [comment]
When reading again I realise that URL field is not used just for `source` but also for `value` and various other fields. That makes the recommendation to use GRID even more problematic.

**Comment by cdvoisin** [comment]
Updated in PR 27 to address this concern.
