### ISSUE TITLE
Several definitions for registered access

### ISSUE THREAD

**Issue by mikael-linden** [ga4gh-duri/ga4gh-duri.github.io#25]
I suggest you refine the references to registered access (SOM Dyke et al, https://doi.org/10.1038/s41431-018-0219-y) in a way that better supports a world where several definitions of registered access may co-exists. It is also possible some day SOM Dyke et al come with a new, improved definition of registered access, making current spec problematic. 
For instance, Encodung use cases: registered access has currently text:
_To meet the requirements of Registered Access to data, a user needs to have all of the following Passport Visas:_

**Comment by cdvoisin** [comment]
Added wording for versioning in PR 27.
