### ISSUE TITLE
ga4gh.ResearcherStatus

### ISSUE THREAD

**Issue by MKonopko** [ga4gh-duri/ga4gh-duri.github.io#3]
https://github.com/ga4gh-duri/ga4gh-duri.github.io/blob/master/researcher_ids/RI_Claims_RFC.md#ga4ghresearcherstatus

From Mikael Linden
Perhaps it is necessary to clarify the position of this claim vs. AffiliationAndRole.

From @cdvoisin
I've added a second sentence to the first bullet and the second bullet is entirely new. PTAL.
+stephanie.dyke@mcin.ca PTAL as well.

From Mikael Linden
I'm observing some of the discussions in the "researcher definitions" document could better fit this attribute ("researcher by vouching", "researcher as defined by NIH", librarycard/passport) while the rest fit AffiliationAndRole.

From Stephanie Dyke
let's discuss and describe accordingly. I removed the second part of the first bullet as we want to keep the term Bona Fide for Registered Access status.

From @cdvoisin
Can we resolve this issue on the doc, but keep it alive as part of the "researcher definition" discussion?
Discussed with Mikael today. We would like a separate issue tracked that discusses clear definitions of when to use ResearcherStatus vs. AffiliationAndRole or to merge claims if there is no clear separation.

**Comment by cdvoisin** [comment]
I believe this issue has been resolved by reducing standard role terminology for v1 and also allowing custom roles to be defined to meet specific needs.
