### ISSUE TITLE
Example RI Claims

### ISSUE THREAD

**Issue by MKonopko** [ga4gh-duri/ga4gh-duri.github.io#4]
https://github.com/ga4gh-duri/ga4gh-duri.github.io/blob/master/researcher_ids/RI_Claims_RFC.md#example-ri-claims

From Martin Kuba

"AcceptedTermsAndPolicies": [
    "value": "https://doi.org/10.1038/s41431-018-0219-y",
    "source": "https://grid.ac/institutes/grid.240952.8",
    "by": "self",
    "asserted": 1549680000,
    "expires": 1581208000

The example is not a valid JSON, the square brackets [ ] denote an array, but the content looks like object. Probably curly braces { } are missing around the values, so it should be an array of objects.

**Comment by cdvoisin** [comment]
Fixed the example before it was ported to Github.
