### ISSUE TITLE
The QuickLinks link for AAI profile points to the work in progress Google doc, not the actual spec

### ISSUE THREAD

**Issue by andrewpatto** [ga4gh-duri/ga4gh-duri.github.io#50]
It seems there is a bitly link that is still pointing to the Draft RFC google doc..

In this section

https://github.com/ga4gh-duri/ga4gh-duri.github.io/tree/master/researcher_ids#quick-links

The other links on the page for AAI seem to go to a markdown doc (also Draft RFC but I presume the correct spot?).

**Comment by cdvoisin** [comment]
Thanks for your feedback! This link has been fixed in PR#51.
